server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: laboratorio-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/db_laboratorio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&allowMultiQueries=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:galito2002}
    'driver-class-name': com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        'format_sql': true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 'classpath:db/migration'

logging:
  level:
    '[com.solca.laboratorio]': DEBUG
    '[org.springframework.web]': INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
