INSERT INTO consultas (id_paciente_regional, sede, fecha_consulta, especialidad, diagnostico, tratamiento, medico, notas, examen_fisico, observaciones, recomendaciones)
VALUES
    ('PAC-00001', 'SOLCA-CUENCA', '2026-01-15', 'Oncología', 'Carcinoma basocelular en etapa temprana', 'Resección quirúrgica programada', 'Dr. Ricardo Merchan', 'Paciente refiere lesión en región malar izquierda de crecimiento lento', 'PA: 120/80, FC: 72, T: 36.5°C. Lesión nodular pigmentada de 8mm en región malar izquierda', 'Paciente en buenas condiciones generales', 'Programar resección ambulatoria, control en 7 días'),
    ('PAC-00001', 'SOLCA-CUENCA', '2026-02-20', 'Cirugía Oncológica', 'Post-operatorio de resección', 'Cuidados de herida, control en 30 días', 'Dr. Ricardo Merchan', 'Paciente asintomático, herida quirúrgica en evolución favorable', 'PA: 118/75, FC: 68, T: 36.6°C. Herida quirúrgica limpia, sin signos de infección', 'Evolución favorable, bordes quirúrgicos negativos', 'Continuar cuidados locales, control en 30 días'),
    ('PAC-00001', 'SOLCA-QUITO', '2026-04-10', 'Radioterapia', 'Evaluación para tratamiento adyuvante', 'Programar sesiones de radioterapia', 'Dra. Patricia Suárez', 'Paciente refiere molestias leves en zona operatoria', 'PA: 122/78, FC: 70, T: 36.4°C. Cicatriz normocrómica', 'No contraindicaciones para radioterapia', 'Iniciar sesiones de radioterapia en 2 semanas'),
    ('PAC-00002', 'SOLCA-CUENCA', '2026-03-05', 'Ginecología Oncológica', 'Nódulo tiroideo sospechoso', 'Biopsia por aspiración con aguja fina', 'Dra. Carmen Torres', 'Paciente refiere aumento de volumen en cuello, disfagia leve', 'PA: 130/85, FC: 76, T: 36.7°C. Nódulo tiroideo derecho palpable de 2cm', 'Se solicita ecografía tiroidea y perfil hormonal', 'Realizar BAAF guiada por ecografía, control en 15 días'),
    ('PAC-00003', 'SOLCA-MANABI', '2026-02-28', 'Oncología', 'Adenocarcinoma de colon Estadio II', 'Colectomía parcial + quimioterapia adyuvante', 'Dr. Luis Zambrano', 'Paciente refiere dolor abdominal tipo cólico, sangrado oculto positivo', 'PA: 140/90, FC: 80, T: 36.8°C. Abdomen blando, doloroso en FID', 'Se confirma diagnóstico por colonoscopia', 'Programar cirugía y valoración prequirúrgica completa'),
    ('PAC-00004', 'SOLCA-QUITO', '2026-01-10', 'Hematología', 'Leucemia linfocítica crónica', 'Protocolo de quimioterapia FCR', 'Dr. Marco Jiménez', 'Paciente asintomática, hallazgo incidental en hemograma', 'PA: 110/70, FC: 65, T: 36.5°C. Adenopatías cervicales y axilares palpables', 'Citometría de flujo confirma LLC', 'Iniciar protocolo FCR, controles semanales'),
    ('PAC-00005', 'SOLCA-MANABI', '2026-03-22', 'Oncología', 'Cáncer de próstata localizado', 'Prostatectomía radical robótica', 'Dr. Luis Zambrano', 'Paciente refiere disuria, nicturia, PSA elevado en control rutinario', 'PA: 145/92, FC: 74, T: 36.6°C. Tacto rectal: próstata aumentada de tamaño, nódulo palpable', 'Biopsia confirmó adenocarcinoma Gleason 7', 'Programar prostatectomía radical robótica, suspender anticoagulantes');
