ALTER TABLE consultas
  ADD COLUMN peso DECIMAL(5,2) DEFAULT 0 AFTER recomendaciones,
  ADD COLUMN talla DECIMAL(5,2) DEFAULT 0 AFTER peso,
  ADD COLUMN imc DECIMAL(4,1) DEFAULT 0 AFTER talla,
  ADD COLUMN clasificacion_oms VARCHAR(50) DEFAULT '' AFTER imc,
  ADD COLUMN superficie_corporal DECIMAL(4,2) DEFAULT 0 AFTER clasificacion_oms,
  ADD COLUMN riesgo_cardiovascular VARCHAR(20) DEFAULT '' AFTER superficie_corporal,
  ADD COLUMN presion_arterial VARCHAR(10) DEFAULT '' AFTER riesgo_cardiovascular,
  ADD COLUMN frecuencia_cardiaca INT DEFAULT 0 AFTER presion_arterial,
  ADD COLUMN temperatura DECIMAL(4,1) DEFAULT 0 AFTER frecuencia_cardiaca,
  ADD COLUMN frecuencia_respiratoria INT DEFAULT 0 AFTER temperatura,
  ADD COLUMN saturacion_oxigeno INT DEFAULT 0 AFTER frecuencia_respiratoria,
  -- Gineco-obstétricos
  ADD COLUMN menarquia INT DEFAULT 0 AFTER saturacion_oxigeno,
  ADD COLUMN fum DATE AFTER menarquia,
  ADD COLUMN fpp DATE AFTER fum,
  ADD COLUMN edad_gestacional INT DEFAULT 0 AFTER fpp,
  ADD COLUMN gestas INT DEFAULT 0 AFTER edad_gestacional,
  ADD COLUMN partos INT DEFAULT 0 AFTER gestas,
  ADD COLUMN cesareas INT DEFAULT 0 AFTER partos,
  ADD COLUMN abortos INT DEFAULT 0 AFTER cesareas,
  ADD COLUMN hijos_vivos INT DEFAULT 0 AFTER abortos,
  ADD COLUMN hijos_muertos INT DEFAULT 0 AFTER hijos_vivos,
  ADD COLUMN embarazos_ectopicos INT DEFAULT 0 AFTER hijos_muertos,
  ADD COLUMN embarazos_multiples INT DEFAULT 0 AFTER embarazos_ectopicos,
  ADD COLUMN metodo_anticonceptivo VARCHAR(100) DEFAULT '' AFTER embarazos_multiples,
  ADD COLUMN lactancia VARCHAR(50) DEFAULT '' AFTER metodo_anticonceptivo,
  ADD COLUMN menopausia VARCHAR(50) DEFAULT '' AFTER lactancia,
  ADD COLUMN pap VARCHAR(100) DEFAULT '' AFTER menopausia,
  ADD COLUMN colposcopia VARCHAR(100) DEFAULT '' AFTER pap,
  ADD COLUMN mamografia VARCHAR(100) DEFAULT '' AFTER colposcopia,
  ADD COLUMN antecedentes_ginecologicos TEXT AFTER mamografia,
  -- Diagnósticos estructurados
  ADD COLUMN diagnostico_principal_cie10 VARCHAR(10) DEFAULT '' AFTER antecedentes_ginecologicos,
  ADD COLUMN diagnostico_principal_desc TEXT,
  ADD COLUMN diagnostico_secundario_cie10 VARCHAR(10) DEFAULT '',
  ADD COLUMN diagnostico_secundario_desc TEXT,
  ADD COLUMN tipo_diagnostico VARCHAR(20) DEFAULT 'PRESUNTIVO',
  ADD COLUMN alergias_consulta TEXT,
  ADD COLUMN plan_tratamiento TEXT;

CREATE INDEX idx_consulta_cie10 ON consultas(diagnostico_principal_cie10);