CREATE TABLE IF NOT EXISTS cie10 (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    capitulo VARCHAR(100),
    categoria VARCHAR(10),
    INDEX idx_cie10_codigo (codigo),
    INDEX idx_cie10_categoria (categoria),
    INDEX idx_cie10_descripcion (descripcion(100))
);

INSERT IGNORE INTO cie10 (codigo, descripcion, capitulo, categoria) VALUES
-- Capítulo I: Ciertas enfermedades infecciosas y parasitarias
('A00', 'Cólera', 'Infecciosas', 'A00-A09'),
('A01', 'Fiebres tifoidea y paratifoidea', 'Infecciosas', 'A00-A09'),
('A02', 'Otras infecciones debidas a Salmonella', 'Infecciosas', 'A00-A09'),
('A03', 'Shigelosis', 'Infecciosas', 'A00-A09'),
('A04', 'Otras infecciones intestinales bacterianas', 'Infecciosas', 'A00-A09'),
('A05', 'Otras intoxicaciones alimentarias bacterianas', 'Infecciosas', 'A00-A09'),
('A06', 'Amebiasis', 'Infecciosas', 'A00-A09'),
('A07', 'Otras enfermedades intestinales debidas a protozoarios', 'Infecciosas', 'A00-A09'),
('A08', 'Infecciones intestinales debidas a virus y otros organismos', 'Infecciosas', 'A00-A09'),
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'Infecciosas', 'A00-A09'),
('A15', 'Tuberculosis respiratoria', 'Infecciosas', 'A15-A19'),
('A16', 'Tuberculosis respiratoria no confirmada', 'Infecciosas', 'A15-A19'),
('A17', 'Tuberculosis del sistema nervioso', 'Infecciosas', 'A15-A19'),
('A18', 'Tuberculosis de otros órganos', 'Infecciosas', 'A15-A19'),
('A19', 'Tuberculosis miliar', 'Infecciosas', 'A15-A19'),
('A20', 'Peste', 'Infecciosas', 'A20-A28'),
('A21', 'Tularemia', 'Infecciosas', 'A20-A28'),
('A22', 'Ántrax', 'Infecciosas', 'A20-A28'),
('A23', 'Brucelosis', 'Infecciosas', 'A20-A28'),
('A24', 'Muermo y melioidosis', 'Infecciosas', 'A20-A28'),
('A25', 'Fiebre por mordedura de rata', 'Infecciosas', 'A20-A28'),
('A26', 'Erisipeloide', 'Infecciosas', 'A20-A28'),
('A27', 'Leptospirosis', 'Infecciosas', 'A20-A28'),
('A28', 'Otras enfermedades bacterianas zoonóticas', 'Infecciosas', 'A20-A28'),
('A30', 'Lepra', 'Infecciosas', 'A30-A49'),
('A31', 'Infecciones debidas a otras micobacterias', 'Infecciosas', 'A30-A49'),
('A32', 'Listeriosis', 'Infecciosas', 'A30-A49'),
('A33', 'Tétanos neonatal', 'Infecciosas', 'A30-A49'),
('A34', 'Tétanos obstétrico', 'Infecciosas', 'A30-A49'),
('A35', 'Otros tétanos', 'Infecciosas', 'A30-A49'),
('A36', 'Difteria', 'Infecciosas', 'A30-A49'),
('A37', 'Tos ferina', 'Infecciosas', 'A30-A49'),
('A38', 'Escarlatina', 'Infecciosas', 'A30-A49'),
('A39', 'Infección meningocócica', 'Infecciosas', 'A30-A49'),
('A40', 'Septicemia estreptocócica', 'Infecciosas', 'A30-A49'),
('A41', 'Otras septicemias', 'Infecciosas', 'A30-A49'),
('A42', 'Actinomicosis', 'Infecciosas', 'A30-A49'),
('A43', 'Nocardiosis', 'Infecciosas', 'A30-A49'),
('A44', 'Bartonelosis', 'Infecciosas', 'A30-A49'),
('A46', 'Erisipela', 'Infecciosas', 'A30-A49'),
('A48', 'Otras enfermedades bacterianas', 'Infecciosas', 'A30-A49'),
('A49', 'Infección bacteriana de sitio no especificado', 'Infecciosas', 'A30-A49'),
('A50', 'Sífilis congénita', 'Infecciosas', 'A50-A64'),
('A51', 'Sífilis primaria', 'Infecciosas', 'A50-A64'),
('A52', 'Sífilis secundaria', 'Infecciosas', 'A50-A64'),
('A53', 'Sífilis tardía', 'Infecciosas', 'A50-A64'),
('A54', 'Infección gonocócica', 'Infecciosas', 'A50-A64'),
('A55', 'Linfogranuloma venéreo por clamidias', 'Infecciosas', 'A50-A64'),
('A56', 'Otras infecciones de transmisión sexual por clamidias', 'Infecciosas', 'A50-A64'),
('A57', 'Chancro blando', 'Infecciosas', 'A50-A64'),
('A58', 'Granuloma inguinal', 'Infecciosas', 'A50-A64'),
('A59', 'Tricomoniasis', 'Infecciosas', 'A50-A64'),
('A60', 'Infección anogenital por virus del herpes', 'Infecciosas', 'A50-A64'),
('A63', 'Otras enfermedades de transmisión sexual', 'Infecciosas', 'A50-A64'),
('A64', 'Enfermedad de transmisión sexual no especificada', 'Infecciosas', 'A50-A64'),
('A65', 'Sífilis no venérea', 'Infecciosas', 'A65-A69'),
('A66', 'Frambesia', 'Infecciosas', 'A65-A69'),
('A67', 'Pinta', 'Infecciosas', 'A65-A69'),
('A68', 'Fiebres recurrentes', 'Infecciosas', 'A65-A69'),
('A69', 'Otras infecciones por espiroquetas', 'Infecciosas', 'A65-A69'),
('A70', 'Infección por Chlamydia psittaci', 'Infecciosas', 'A70-A74'),
('A71', 'Tracoma', 'Infecciosas', 'A70-A74'),
('A74', 'Otras enfermedades por clamidias', 'Infecciosas', 'A70-A74'),
('A75', 'Tifus epidémico', 'Infecciosas', 'A75-A79'),
('A77', 'Fiebre maculosa', 'Infecciosas', 'A75-A79'),
('A78', 'Fiebre Q', 'Infecciosas', 'A75-A79'),
('A79', 'Otras rickettsiosis', 'Infecciosas', 'A75-A79'),
('A80', 'Poliomielitis aguda', 'Infecciosas', 'A80-A89'),
('A81', 'Enfermedad de Creutzfeldt-Jakob', 'Infecciosas', 'A80-A89'),
('A82', 'Rabia', 'Infecciosas', 'A80-A89'),
('A83', 'Encefalitis viral', 'Infecciosas', 'A80-A89'),
('A84', 'Encefalitis viral transmitida por garrapatas', 'Infecciosas', 'A80-A89'),
('A85', 'Otras encefalitis virales', 'Infecciosas', 'A80-A89'),
('A86', 'Encefalitis viral no especificada', 'Infecciosas', 'A80-A89'),
('A87', 'Meningitis viral', 'Infecciosas', 'A80-A89'),
('A88', 'Otras infecciones virales del SNC', 'Infecciosas', 'A80-A89'),
('A89', 'Infección viral del SNC no especificada', 'Infecciosas', 'A80-A89'),
('A90', 'Fiebre del dengue', 'Infecciosas', 'A90-A99'),
('A91', 'Fiebre del dengue hemorrágico', 'Infecciosas', 'A90-A99'),
('A92', 'Otras fiebres virales transmitidas por mosquitos', 'Infecciosas', 'A90-A99'),
('A93', 'Otras fiebres virales transmitidas por artrópodos', 'Infecciosas', 'A90-A99'),
('A94', 'Fiebre viral transmitida por artrópodos no especificada', 'Infecciosas', 'A90-A99'),
('A95', 'Fiebre amarilla', 'Infecciosas', 'A90-A99'),
('A96', 'Fiebre hemorrágica por arenavirus', 'Infecciosas', 'A90-A99'),
('A97', 'Dengue grave', 'Infecciosas', 'A90-A99'),
('A98', 'Otras fiebres hemorrágicas virales', 'Infecciosas', 'A90-A99'),
('A99', 'Fiebre hemorrágica viral no especificada', 'Infecciosas', 'A90-A99'),
('B00', 'Infecciones por virus del herpes', 'Infecciosas', 'B00-B09'),
('B01', 'Varicela', 'Infecciosas', 'B00-B09'),
('B02', 'Herpes zóster', 'Infecciosas', 'B00-B09'),
('B03', 'Viruela', 'Infecciosas', 'B00-B09'),
('B04', 'Viruela de los monos', 'Infecciosas', 'B00-B09'),
('B05', 'Sarampión', 'Infecciosas', 'B00-B09'),
('B06', 'Rubéola', 'Infecciosas', 'B00-B09'),
('B07', 'Verrugas virales', 'Infecciosas', 'B00-B09'),
('B08', 'Otras infecciones virales con lesiones cutáneas', 'Infecciosas', 'B00-B09'),
('B09', 'Infección viral no especificada con lesiones cutáneas', 'Infecciosas', 'B00-B09'),
('B15', 'Hepatitis aguda tipo A', 'Infecciosas', 'B15-B19'),
('B16', 'Hepatitis aguda tipo B', 'Infecciosas', 'B15-B19'),
('B17', 'Otras hepatitis virales agudas', 'Infecciosas', 'B15-B19'),
('B18', 'Hepatitis viral crónica', 'Infecciosas', 'B15-B19'),
('B19', 'Hepatitis viral no especificada', 'Infecciosas', 'B15-B19'),
('B20', 'Enfermedad por VIH resultante en infecciones micobacterianas', 'Infecciosas', 'B20-B24'),
('B21', 'Enfermedad por VIH resultante en neoplasias malignas', 'Infecciosas', 'B20-B24'),
('B22', 'Enfermedad por VIH resultante en otras enfermedades', 'Infecciosas', 'B20-B24'),
('B23', 'Enfermedad por VIH resultante en otras afecciones', 'Infecciosas', 'B20-B24'),
('B24', 'Enfermedad por VIH no especificada', 'Infecciosas', 'B20-B24'),
('B25', 'Enfermedad por citomegalovirus', 'Infecciosas', 'B25-B34'),
('B26', 'Parotiditis infecciosa', 'Infecciosas', 'B25-B34'),
('B27', 'Mononucleosis infecciosa', 'Infecciosas', 'B25-B34'),
('B30', 'Conjuntivitis viral', 'Infecciosas', 'B25-B34'),
('B31', 'Otras infecciones virales', 'Infecciosas', 'B25-B34'),
('B33', 'Otras enfermedades virales', 'Infecciosas', 'B25-B34'),
('B34', 'Infección viral de sitio no especificado', 'Infecciosas', 'B25-B34'),
('B35', 'Dermatofitosis', 'Infecciosas', 'B35-B49'),
('B36', 'Otras micosis superficiales', 'Infecciosas', 'B35-B49'),
('B37', 'Candidiasis', 'Infecciosas', 'B35-B49'),
('B38', 'Coccidioidomicosis', 'Infecciosas', 'B35-B49'),
('B39', 'Histoplasmosis', 'Infecciosas', 'B35-B49'),
('B40', 'Blastomicosis', 'Infecciosas', 'B35-B49'),
('B41', 'Paracoccidioidomicosis', 'Infecciosas', 'B35-B49'),
('B42', 'Esporotricosis', 'Infecciosas', 'B35-B49'),
('B43', 'Cromomicosis', 'Infecciosas', 'B35-B49'),
('B44', 'Aspergilosis', 'Infecciosas', 'B35-B49'),
('B45', 'Criptococosis', 'Infecciosas', 'B35-B49'),
('B46', 'Cigomicosis', 'Infecciosas', 'B35-B49'),
('B47', 'Micetoma', 'Infecciosas', 'B35-B49'),
('B48', 'Otras micosis', 'Infecciosas', 'B35-B49'),
('B49', 'Micosis no especificada', 'Infecciosas', 'B35-B49'),
('B50', 'Paludismo por Plasmodium falciparum', 'Infecciosas', 'B50-B64'),
('B51', 'Paludismo por Plasmodium vivax', 'Infecciosas', 'B50-B64'),
('B52', 'Paludismo por Plasmodium malariae', 'Infecciosas', 'B50-B64'),
('B53', 'Otras formas de paludismo', 'Infecciosas', 'B50-B64'),
('B54', 'Paludismo no especificado', 'Infecciosas', 'B50-B64'),
('B55', 'Leishmaniasis', 'Infecciosas', 'B50-B64'),
('B56', 'Tripanosomiasis africana', 'Infecciosas', 'B50-B64'),
('B57', 'Enfermedad de Chagas', 'Infecciosas', 'B50-B64'),
('B58', 'Toxoplasmosis', 'Infecciosas', 'B50-B64'),
('B59', 'Neumocistosis', 'Infecciosas', 'B50-B64'),
('B60', 'Otras enfermedades parasitarias', 'Infecciosas', 'B50-B64'),
('B64', 'Enfermedad parasitaria no especificada', 'Infecciosas', 'B50-B64'),
('B65', 'Esquistosomiasis', 'Infecciosas', 'B65-B83'),
('B66', 'Otras infecciones por trematodos', 'Infecciosas', 'B65-B83'),
('B67', 'Equinococosis', 'Infecciosas', 'B65-B83'),
('B68', 'Teniasis', 'Infecciosas', 'B65-B83'),
('B69', 'Cisticercosis', 'Infecciosas', 'B65-B83'),
('B70', 'Difilobotriasis y esparganosis', 'Infecciosas', 'B65-B83'),
('B71', 'Otras infecciones por cestodos', 'Infecciosas', 'B65-B83'),
('B72', 'Dracunculosis', 'Infecciosas', 'B65-B83'),
('B73', 'Oncocercosis', 'Infecciosas', 'B65-B83'),
('B74', 'Filariasis', 'Infecciosas', 'B65-B83'),
('B75', 'Triquinosis', 'Infecciosas', 'B65-B83'),
('B76', 'Anquilostomiasis', 'Infecciosas', 'B65-B83'),
('B77', 'Ascaridiasis', 'Infecciosas', 'B65-B83'),
('B78', 'Estrongiloidiasis', 'Infecciosas', 'B65-B83'),
('B79', 'Tricuriasis', 'Infecciosas', 'B65-B83'),
('B80', 'Enterobiasis', 'Infecciosas', 'B65-B83'),
('B81', 'Otras helmintiasis intestinales', 'Infecciosas', 'B65-B83'),
('B82', 'Parasitosis intestinal no especificada', 'Infecciosas', 'B65-B83'),
('B83', 'Otras helmintiasis', 'Infecciosas', 'B65-B83'),
('B85', 'Pediculosis', 'Infecciosas', 'B85-B89'),
('B86', 'Escabiosis', 'Infecciosas', 'B85-B89'),
('B87', 'Miasis', 'Infecciosas', 'B85-B89'),
('B88', 'Otras infestaciones', 'Infecciosas', 'B85-B89'),
('B89', 'Enfermedad parasitaria no especificada', 'Infecciosas', 'B85-B89'),
('B90', 'Secuelas de tuberculosis', 'Infecciosas', 'B90-B94'),
('B91', 'Secuelas de poliomielitis', 'Infecciosas', 'B90-B94'),
('B92', 'Secuelas de lepra', 'Infecciosas', 'B90-B94'),
('B94', 'Secuelas de otras enfermedades infecciosas', 'Infecciosas', 'B90-B94'),
('B95', 'Estreptococos como causa de enfermedades clasificadas en otros capítulos', 'Infecciosas', 'B95-B97'),
('B96', 'Otros agentes bacterianos como causa de enfermedades', 'Infecciosas', 'B95-B97'),
('B97', 'Agentes virales como causa de enfermedades', 'Infecciosas', 'B95-B97'),
('B99', 'Otras enfermedades infecciosas', 'Infecciosas', 'B99'),
-- Chapter II: Neoplasias
('C00', 'Tumor maligno del labio', 'Neoplasias', 'C00-C14'),
('C01', 'Tumor maligno de la base de la lengua', 'Neoplasias', 'C00-C14'),
('C02', 'Tumor maligno de otras partes de la lengua', 'Neoplasias', 'C00-C14'),
('C03', 'Tumor maligno de la encía', 'Neoplasias', 'C00-C14'),
('C04', 'Tumor maligno del piso de la boca', 'Neoplasias', 'C00-C14'),
('C05', 'Tumor maligno del paladar', 'Neoplasias', 'C00-C14'),
('C06', 'Tumor maligno de otras partes de la boca', 'Neoplasias', 'C00-C14'),
('C07', 'Tumor maligno de la glándula parótida', 'Neoplasias', 'C00-C14'),
('C08', 'Tumor maligno de otras glándulas salivales', 'Neoplasias', 'C00-C14'),
('C09', 'Tumor maligno de la amígdala', 'Neoplasias', 'C00-C14'),
('C10', 'Tumor maligno de la orofaringe', 'Neoplasias', 'C00-C14'),
('C11', 'Tumor maligno de la nasofaringe', 'Neoplasias', 'C00-C14'),
('C12', 'Tumor maligno del seno piriforme', 'Neoplasias', 'C00-C14'),
('C13', 'Tumor maligno de la hipofaringe', 'Neoplasias', 'C00-C14'),
('C14', 'Tumor maligno del labio, cavidad oral y faringe', 'Neoplasias', 'C00-C14'),
('C15', 'Tumor maligno del esófago', 'Neoplasias', 'C15-C26'),
('C16', 'Tumor maligno del estómago', 'Neoplasias', 'C15-C26'),
('C17', 'Tumor maligno del intestino delgado', 'Neoplasias', 'C15-C26'),
('C18', 'Tumor maligno del colon', 'Neoplasias', 'C15-C26'),
('C19', 'Tumor maligno de la unión rectosigmoidea', 'Neoplasias', 'C15-C26'),
('C20', 'Tumor maligno del recto', 'Neoplasias', 'C15-C26'),
('C21', 'Tumor maligno del ano y conducto anal', 'Neoplasias', 'C15-C26'),
('C22', 'Tumor maligno del hígado', 'Neoplasias', 'C15-C26'),
('C23', 'Tumor maligno de la vesícula biliar', 'Neoplasias', 'C15-C26'),
('C24', 'Tumor maligno del páncreas', 'Neoplasias', 'C15-C26'),
('C25', 'Tumor maligno de otras partes del sistema digestivo', 'Neoplasias', 'C15-C26'),
('C26', 'Tumor maligno del sistema digestivo', 'Neoplasias', 'C15-C26'),
('C30', 'Tumor maligno de la cavidad nasal', 'Neoplasias', 'C30-C39'),
('C31', 'Tumor maligno de los senos paranasales', 'Neoplasias', 'C30-C39'),
('C32', 'Tumor maligno de la laringe', 'Neoplasias', 'C30-C39'),
('C33', 'Tumor maligno de la tráquea', 'Neoplasias', 'C30-C39'),
('C34', 'Tumor maligno de los bronquios y del pulmón', 'Neoplasias', 'C30-C39'),
('C37', 'Tumor maligno del timo', 'Neoplasias', 'C30-C39'),
('C38', 'Tumor maligno del mediastino', 'Neoplasias', 'C30-C39'),
('C39', 'Tumor maligno del sistema respiratorio', 'Neoplasias', 'C30-C39'),
('C40', 'Tumor maligno del hueso y cartílago', 'Neoplasias', 'C40-C41'),
('C41', 'Tumor maligno del hueso y cartílago articular', 'Neoplasias', 'C40-C41'),
('C43', 'Melanoma maligno de la piel', 'Neoplasias', 'C43-C44'),
('C44', 'Otros tumores malignos de la piel', 'Neoplasias', 'C43-C44'),
('C45', 'Mesotelioma', 'Neoplasias', 'C45-C49'),
('C46', 'Sarcoma de Kaposi', 'Neoplasias', 'C45-C49'),
('C47', 'Tumor maligno de los nervios periféricos', 'Neoplasias', 'C45-C49'),
('C48', 'Tumor maligno del peritoneo', 'Neoplasias', 'C45-C49'),
('C49', 'Tumor maligno del tejido conjuntivo', 'Neoplasias', 'C45-C49'),
('C50', 'Tumor maligno de la mama', 'Neoplasias', 'C50-C50'),
('C51', 'Tumor maligno de la vulva', 'Neoplasias', 'C51-C58'),
('C52', 'Tumor maligno de la vagina', 'Neoplasias', 'C51-C58'),
('C53', 'Tumor maligno del cuello del útero', 'Neoplasias', 'C51-C58'),
('C54', 'Tumor maligno del cuerpo del útero', 'Neoplasias', 'C51-C58'),
('C55', 'Tumor maligno del útero', 'Neoplasias', 'C51-C58'),
('C56', 'Tumor maligno del ovario', 'Neoplasias', 'C51-C58'),
('C57', 'Tumor maligno de otros órganos genitales femeninos', 'Neoplasias', 'C51-C58'),
('C58', 'Tumor maligno de la placenta', 'Neoplasias', 'C51-C58'),
('C60', 'Tumor maligno del pene', 'Neoplasias', 'C60-C63'),
('C61', 'Tumor maligno de la próstata', 'Neoplasias', 'C60-C63'),
('C62', 'Tumor maligno del testículo', 'Neoplasias', 'C60-C63'),
('C63', 'Tumor maligno de otros órganos genitales masculinos', 'Neoplasias', 'C60-C63'),
('C64', 'Tumor maligno del riñón', 'Neoplasias', 'C64-C68'),
('C65', 'Tumor maligno de la pelvis renal', 'Neoplasias', 'C64-C68'),
('C66', 'Tumor maligno del uréter', 'Neoplasias', 'C64-C68'),
('C67', 'Tumor maligno de la vejiga urinaria', 'Neoplasias', 'C64-C68'),
('C68', 'Tumor maligno de otros órganos urinarios', 'Neoplasias', 'C64-C68'),
('C69', 'Tumor maligno del ojo', 'Neoplasias', 'C69-C72'),
('C70', 'Tumor maligno de las meninges', 'Neoplasias', 'C69-C72'),
('C71', 'Tumor maligno del encéfalo', 'Neoplasias', 'C69-C72'),
('C72', 'Tumor maligno de la médula espinal', 'Neoplasias', 'C69-C72'),
('C73', 'Tumor maligno de la glándula tiroides', 'Neoplasias', 'C73-C75'),
('C74', 'Tumor maligno de la glándula suprarrenal', 'Neoplasias', 'C73-C75'),
('C75', 'Tumor maligno de otras glándulas endocrinas', 'Neoplasias', 'C73-C75'),
('C76', 'Tumor maligno de otros sitios mal definidos', 'Neoplasias', 'C76-C80'),
('C77', 'Tumor maligno secundario de los ganglios linfáticos', 'Neoplasias', 'C77-C80'),
('C78', 'Tumor maligno secundario del sistema respiratorio', 'Neoplasias', 'C77-C80'),
('C79', 'Tumor maligno secundario de otros sitios', 'Neoplasias', 'C77-C80'),
('C80', 'Tumor maligno sin especificación de sitio', 'Neoplasias', 'C77-C80'),
('C81', 'Enfermedad de Hodgkin', 'Neoplasias', 'C81-C96'),
('C82', 'Linfoma folicular', 'Neoplasias', 'C81-C96'),
('C83', 'Linfoma difuso de células B', 'Neoplasias', 'C81-C96'),
('C84', 'Linfoma de células T', 'Neoplasias', 'C81-C96'),
('C85', 'Otros linfomas no Hodgkin', 'Neoplasias', 'C81-C96'),
('C86', 'Otras neoplasias de células T', 'Neoplasias', 'C81-C96'),
('C88', 'Enfermedades inmunoproliferativas', 'Neoplasias', 'C81-C96'),
('C90', 'Mieloma múltiple', 'Neoplasias', 'C81-C96'),
('C91', 'Leucemia linfocítica', 'Neoplasias', 'C81-C96'),
('C92', 'Leucemia mieloide', 'Neoplasias', 'C81-C96'),
('C93', 'Leucemia monocítica', 'Neoplasias', 'C81-C96'),
('C94', 'Otras leucemias', 'Neoplasias', 'C81-C96'),
('C95', 'Leucemia de células no especificadas', 'Neoplasias', 'C81-C96'),
('C96', 'Otras neoplasias malignas del tejido linfático', 'Neoplasias', 'C81-C96'),
('C97', 'Neoplasias malignas de sitios múltiples independientes', 'Neoplasias', 'C97'),
-- Chapter III: Enfermedades de la sangre
('D50', 'Anemia por deficiencia de hierro', 'Sangre', 'D50-D64'),
('D51', 'Anemia por deficiencia de vitamina B12', 'Sangre', 'D50-D64'),
('D52', 'Anemia por deficiencia de folato', 'Sangre', 'D50-D64'),
('D53', 'Otras anemias nutricionales', 'Sangre', 'D50-D64'),
('D55', 'Anemia por trastornos enzimáticos', 'Sangre', 'D50-D64'),
('D56', 'Talasemia', 'Sangre', 'D50-D64'),
('D57', 'Trastornos falciformes', 'Sangre', 'D50-D64'),
('D58', 'Otras anemias hemolíticas hereditarias', 'Sangre', 'D50-D64'),
('D59', 'Anemia hemolítica adquirida', 'Sangre', 'D50-D64'),
('D60', 'Aplasia pura de células rojas', 'Sangre', 'D50-D64'),
('D61', 'Otras anemias aplásicas', 'Sangre', 'D50-D64'),
('D62', 'Anemia aguda posthemorrágica', 'Sangre', 'D50-D64'),
('D63', 'Anemia en enfermedades crónicas', 'Sangre', 'D50-D64'),
('D64', 'Anemia no especificada', 'Sangre', 'D50-D64'),
('D65', 'Coagulación intravascular diseminada', 'Sangre', 'D65-D69'),
('D66', 'Deficiencia hereditaria de factor VIII', 'Sangre', 'D65-D69'),
('D67', 'Deficiencia hereditaria de factor IX', 'Sangre', 'D65-D69'),
('D68', 'Otros defectos de la coagulación', 'Sangre', 'D65-D69'),
('D69', 'Púrpura y otras afecciones hemorrágicas', 'Sangre', 'D65-D69'),
-- Chapter IV: Endocrino
('E00', 'Síndrome de deficiencia de yodo', 'Endocrino', 'E00-E07'),
('E01', 'Trastornos tiroideos por deficiencia de yodo', 'Endocrino', 'E00-E07'),
('E02', 'Hipotiroidismo subclínico por deficiencia de yodo', 'Endocrino', 'E00-E07'),
('E03', 'Otros hipotiroidismos', 'Endocrino', 'E00-E07'),
('E04', 'Otros bocios no tóxicos', 'Endocrino', 'E00-E07'),
('E05', 'Tirotoxicosis', 'Endocrino', 'E00-E07'),
('E06', 'Tiroiditis', 'Endocrino', 'E00-E07'),
('E07', 'Otros trastornos tiroideos', 'Endocrino', 'E00-E07'),
('E10', 'Diabetes mellitus insulinodependiente', 'Endocrino', 'E10-E14'),
('E11', 'Diabetes mellitus no insulinodependiente', 'Endocrino', 'E10-E14'),
('E12', 'Diabetes mellitus asociada con desnutrición', 'Endocrino', 'E10-E14'),
('E13', 'Otras diabetes mellitus', 'Endocrino', 'E10-E14'),
('E14', 'Diabetes mellitus no especificada', 'Endocrino', 'E10-E14'),
('E15', 'Coma hipoglucémico no diabético', 'Endocrino', 'E15-E16'),
('E16', 'Otros trastornos de la secreción interna del páncreas', 'Endocrino', 'E15-E16'),
('E20', 'Hipoparatiroidismo', 'Endocrino', 'E20-E21'),
('E21', 'Hiperparatiroidismo', 'Endocrino', 'E20-E21'),
('E22', 'Hiperfunción de la glándula hipófisis', 'Endocrino', 'E22-E23'),
('E23', 'Hipofunción de la glándula hipófisis', 'Endocrino', 'E22-E23'),
('E24', 'Síndrome de Cushing', 'Endocrino', 'E24-E25'),
('E25', 'Trastornos adrenogenitales', 'Endocrino', 'E24-E25'),
('E26', 'Hiperaldosteronismo', 'Endocrino', 'E26-E27'),
('E27', 'Otros trastornos de la glándula suprarrenal', 'Endocrino', 'E26-E27'),
('E28', 'Disfunción ovárica', 'Endocrino', 'E28-E28'),
('E29', 'Disfunción testicular', 'Endocrino', 'E29-E29'),
('E30', 'Trastornos de la pubertad', 'Endocrino', 'E30-E34'),
('E31', 'Disfunción poliglandular', 'Endocrino', 'E30-E34'),
('E32', 'Enfermedades del timo', 'Endocrino', 'E30-E34'),
('E34', 'Otros trastornos endocrinos', 'Endocrino', 'E30-E34'),
('E40', 'Kwashiorkor', 'Endocrino', 'E40-E46'),
('E41', 'Marasmo nutricional', 'Endocrino', 'E40-E46'),
('E42', 'Kwashiorkor marasmático', 'Endocrino', 'E40-E46'),
('E43', 'Desnutrición proteicocalórica severa', 'Endocrino', 'E40-E46'),
('E44', 'Desnutrición proteicocalórica moderada y leve', 'Endocrino', 'E40-E46'),
('E45', 'Retraso del desarrollo debido a desnutrición', 'Endocrino', 'E40-E46'),
('E46', 'Desnutrición proteicocalórica no especificada', 'Endocrino', 'E40-E46'),
('E50', 'Deficiencia de vitamina A', 'Endocrino', 'E50-E64'),
('E51', 'Deficiencia de tiamina', 'Endocrino', 'E50-E64'),
('E52', 'Deficiencia de niacina', 'Endocrino', 'E50-E64'),
('E53', 'Deficiencia de otras vitaminas del grupo B', 'Endocrino', 'E50-E64'),
('E55', 'Deficiencia de vitamina D', 'Endocrino', 'E50-E64'),
('E56', 'Otras deficiencias vitamínicas', 'Endocrino', 'E50-E64'),
('E58', 'Deficiencia dietética de calcio', 'Endocrino', 'E50-E64'),
('E59', 'Deficiencia dietética de selenio', 'Endocrino', 'E50-E64'),
('E60', 'Deficiencia dietética de zinc', 'Endocrino', 'E50-E64'),
('E61', 'Deficiencia de otros elementos', 'Endocrino', 'E50-E64'),
('E63', 'Otras deficiencias nutricionales', 'Endocrino', 'E50-E64'),
('E64', 'Secuelas de la desnutrición', 'Endocrino', 'E50-E64'),
('E65', 'Obesidad localizada', 'Endocrino', 'E65-E68'),
('E66', 'Obesidad', 'Endocrino', 'E65-E68'),
('E67', 'Otras hiperalimentaciones', 'Endocrino', 'E65-E68'),
('E68', 'Secuelas de hiperalimentación', 'Endocrino', 'E65-E68'),
('E70', 'Trastornos del metabolismo de aminoácidos', 'Endocrino', 'E70-E90'),
('E71', 'Trastornos del metabolismo de ácidos grasos', 'Endocrino', 'E70-E90'),
('E72', 'Trastornos del metabolismo de otros aminoácidos', 'Endocrino', 'E70-E90'),
('E73', 'Intolerancia a la lactosa', 'Endocrino', 'E70-E90'),
('E74', 'Trastornos del metabolismo de los carbohidratos', 'Endocrino', 'E70-E90'),
('E75', 'Trastornos del metabolismo de los esfingolípidos', 'Endocrino', 'E70-E90'),
('E76', 'Trastornos del metabolismo de los glucosaminoglicanos', 'Endocrino', 'E70-E90'),
('E77', 'Trastornos del metabolismo de las glucoproteínas', 'Endocrino', 'E70-E90'),
('E78', 'Trastornos del metabolismo de las lipoproteínas', 'Endocrino', 'E70-E90'),
('E79', 'Trastornos del metabolismo de las purinas', 'Endocrino', 'E70-E90'),
('E80', 'Trastornos del metabolismo de las porfirinas', 'Endocrino', 'E70-E90'),
('E83', 'Trastornos del metabolismo mineral', 'Endocrino', 'E70-E90'),
('E84', 'Fibrosis quística', 'Endocrino', 'E70-E90'),
('E85', 'Amiloidosis', 'Endocrino', 'E70-E90'),
('E86', 'Depleción del volumen de líquidos', 'Endocrino', 'E70-E90'),
('E87', 'Trastornos del equilibrio hidroelectrolítico', 'Endocrino', 'E70-E90'),
('E88', 'Otros trastornos metabólicos', 'Endocrino', 'E70-E90'),
('E89', 'Trastornos endocrinos postquirúrgicos', 'Endocrino', 'E70-E90'),
('E90', 'Trastornos nutricionales y metabólicos en enfermedades', 'Endocrino', 'E70-E90'),
-- Capítulo V: Trastornos mentales
('F00', 'Demencia en enfermedad de Alzheimer', 'Mental', 'F00-F09'),
('F01', 'Demencia vascular', 'Mental', 'F00-F09'),
('F02', 'Demencia en otras enfermedades', 'Mental', 'F00-F09'),
('F03', 'Demencia no especificada', 'Mental', 'F00-F09'),
('F04', 'Síndrome amnésico orgánico', 'Mental', 'F00-F09'),
('F05', 'Delirio inducido por alcohol u otras sustancias', 'Mental', 'F00-F09'),
('F06', 'Otros trastornos mentales debidos a lesión cerebral', 'Mental', 'F00-F09'),
('F07', 'Trastornos de la personalidad debidos a enfermedad cerebral', 'Mental', 'F00-F09'),
('F09', 'Trastorno mental orgánico no especificado', 'Mental', 'F00-F09'),
('F10', 'Trastornos mentales debidos al consumo de alcohol', 'Mental', 'F10-F19'),
('F11', 'Trastornos por consumo de opioides', 'Mental', 'F10-F19'),
('F12', 'Trastornos por consumo de cannabis', 'Mental', 'F10-F19'),
('F13', 'Trastornos por consumo de sedantes', 'Mental', 'F10-F19'),
('F14', 'Trastornos por consumo de cocaína', 'Mental', 'F10-F19'),
('F15', 'Trastornos por consumo de estimulantes', 'Mental', 'F10-F19'),
('F16', 'Trastornos por consumo de alucinógenos', 'Mental', 'F10-F19'),
('F17', 'Trastornos por consumo de tabaco', 'Mental', 'F10-F19'),
('F18', 'Trastornos por inhalación de solventes', 'Mental', 'F10-F19'),
('F19', 'Trastornos por consumo de múltiples drogas', 'Mental', 'F10-F19'),
('F20', 'Esquizofrenia', 'Mental', 'F20-F29'),
('F21', 'Trastorno esquizotípico', 'Mental', 'F20-F29'),
('F22', 'Trastornos de ideas delirantes persistentes', 'Mental', 'F20-F29'),
('F23', 'Trastornos psicóticos agudos', 'Mental', 'F20-F29'),
('F24', 'Trastorno de ideas delirantes inducido', 'Mental', 'F20-F29'),
('F25', 'Trastorno esquizoafectivo', 'Mental', 'F20-F29'),
('F28', 'Otros trastornos psicóticos', 'Mental', 'F20-F29'),
('F29', 'Psicosis no especificada', 'Mental', 'F20-F29'),
('F30', 'Episodio maníaco', 'Mental', 'F30-F39'),
('F31', 'Trastorno bipolar', 'Mental', 'F30-F39'),
('F32', 'Episodio depresivo mayor', 'Mental', 'F30-F39'),
('F33', 'Trastorno depresivo recurrente', 'Mental', 'F30-F39'),
('F34', 'Trastornos del humor persistentes', 'Mental', 'F30-F39'),
('F38', 'Otros trastornos del humor', 'Mental', 'F30-F39'),
('F39', 'Trastorno del humor no especificado', 'Mental', 'F30-F39'),
('F40', 'Trastornos fóbico-ansiosos', 'Mental', 'F40-F48'),
('F41', 'Otros trastornos de ansiedad', 'Mental', 'F40-F48'),
('F42', 'Trastorno obsesivo-compulsivo', 'Mental', 'F40-F48'),
('F43', 'Reacción al estrés severo', 'Mental', 'F40-F48'),
('F44', 'Trastornos de conversión', 'Mental', 'F40-F48'),
('F45', 'Trastornos somatomorfos', 'Mental', 'F40-F48'),
('F48', 'Otros trastornos neuróticos', 'Mental', 'F40-F48'),
('F50', 'Trastornos de la conducta alimentaria', 'Mental', 'F50-F59'),
('F51', 'Trastornos del sueño no orgánicos', 'Mental', 'F50-F59'),
('F52', 'Disfunción sexual', 'Mental', 'F50-F59'),
('F53', 'Trastornos mentales puerperales', 'Mental', 'F50-F59'),
('F54', 'Factores psicológicos en enfermedades somáticas', 'Mental', 'F50-F59'),
('F55', 'Abuso de sustancias que no producen dependencia', 'Mental', 'F50-F59'),
('F59', 'Trastornos de la conducta asociados', 'Mental', 'F50-F59'),
('F60', 'Trastornos de la personalidad', 'Mental', 'F60-F69'),
('F61', 'Trastornos mixtos de la personalidad', 'Mental', 'F60-F69'),
('F62', 'Cambio persistente de la personalidad', 'Mental', 'F60-F69'),
('F63', 'Trastornos de hábitos e impulsos', 'Mental', 'F60-F69'),
('F64', 'Trastornos de la identidad de género', 'Mental', 'F60-F69'),
('F65', 'Trastornos de la preferencia sexual', 'Mental', 'F60-F69'),
('F66', 'Trastornos del desarrollo psicosexual', 'Mental', 'F60-F69'),
('F68', 'Otros trastornos de la personalidad', 'Mental', 'F60-F69'),
('F69', 'Trastorno de la personalidad no especificado', 'Mental', 'F60-F69'),
('F70', 'Retraso mental leve', 'Mental', 'F70-F79'),
('F71', 'Retraso mental moderado', 'Mental', 'F70-F79'),
('F72', 'Retraso mental grave', 'Mental', 'F70-F79'),
('F73', 'Retraso mental profundo', 'Mental', 'F70-F79'),
('F78', 'Otro retraso mental', 'Mental', 'F70-F79'),
('F79', 'Retraso mental no especificado', 'Mental', 'F70-F79'),
('F80', 'Trastornos del desarrollo del habla y lenguaje', 'Mental', 'F80-F89'),
('F81', 'Trastornos del aprendizaje', 'Mental', 'F80-F89'),
('F82', 'Trastorno del desarrollo motor', 'Mental', 'F80-F89'),
('F83', 'Trastornos del desarrollo mixtos', 'Mental', 'F80-F89'),
('F84', 'Trastornos del espectro autista', 'Mental', 'F80-F89'),
('F88', 'Otros trastornos del desarrollo', 'Mental', 'F80-F89'),
('F89', 'Trastorno del desarrollo no especificado', 'Mental', 'F80-F89'),
('F90', 'Trastorno por déficit de atención con hiperactividad', 'Mental', 'F90-F98'),
('F91', 'Trastornos de la conducta', 'Mental', 'F90-F98'),
('F92', 'Trastornos mixtos de la conducta', 'Mental', 'F90-F98'),
('F93', 'Trastornos emocionales de inicio en la infancia', 'Mental', 'F90-F98'),
('F94', 'Trastornos del funcionamiento social infantil', 'Mental', 'F90-F98'),
('F95', 'Trastornos de tics', 'Mental', 'F90-F98'),
('F98', 'Otros trastornos conductuales infantiles', 'Mental', 'F90-F98'),
('F99', 'Trastorno mental no especificado', 'Mental', 'F99'),
-- Chapter VI: Sistema nervioso
('G00', 'Meningitis bacteriana', 'Nervioso', 'G00-G09'),
('G01', 'Meningitis en enfermedades bacterianas', 'Nervioso', 'G00-G09'),
('G02', 'Meningitis en otras enfermedades infecciosas', 'Nervioso', 'G00-G09'),
('G03', 'Meningitis por otras causas', 'Nervioso', 'G00-G09'),
('G04', 'Encefalitis, mielitis y encefalomielitis', 'Nervioso', 'G00-G09'),
('G06', 'Absceso intracraneal', 'Nervioso', 'G00-G09'),
('G08', 'Flebitis intracraneal', 'Nervioso', 'G00-G09'),
('G09', 'Secuelas de enfermedades inflamatorias del SNC', 'Nervioso', 'G00-G09'),
('G10', 'Enfermedad de Huntington', 'Nervioso', 'G10-G13'),
('G11', 'Ataxia hereditaria', 'Nervioso', 'G10-G13'),
('G12', 'Atrofia muscular espinal', 'Nervioso', 'G10-G13'),
('G13', 'Atrofias sistémicas en enfermedades clasificadas', 'Nervioso', 'G10-G13'),
('G20', 'Enfermedad de Parkinson', 'Nervioso', 'G20-G26'),
('G21', 'Parkinsonismo secundario', 'Nervioso', 'G20-G26'),
('G22', 'Parkinsonismo en enfermedades clasificadas', 'Nervioso', 'G20-G26'),
('G23', 'Otras enfermedades degenerativas de los ganglios basales', 'Nervioso', 'G20-G26'),
('G24', 'Distonía', 'Nervioso', 'G20-G26'),
('G25', 'Otros trastornos extrapiramidales', 'Nervioso', 'G20-G26'),
('G26', 'Trastornos extrapiramidales en enfermedades clasificadas', 'Nervioso', 'G20-G26'),
('G30', 'Enfermedad de Alzheimer', 'Nervioso', 'G30-G32'),
('G31', 'Otras enfermedades degenerativas del sistema nervioso', 'Nervioso', 'G30-G32'),
('G32', 'Trastornos degenerativos en enfermedades clasificadas', 'Nervioso', 'G30-G32'),
('G35', 'Esclerosis múltiple', 'Nervioso', 'G35-G37'),
('G36', 'Otras desmielinizaciones agudas', 'Nervioso', 'G35-G37'),
('G37', 'Enfermedades desmielinizantes del SNC', 'Nervioso', 'G35-G37'),
('G40', 'Epilepsia', 'Nervioso', 'G40-G47'),
('G41', 'Estado epiléptico', 'Nervioso', 'G40-G47'),
('G43', 'Migraña', 'Nervioso', 'G40-G47'),
('G44', 'Otras cefaleas', 'Nervioso', 'G40-G47'),
('G45', 'Ataques isquémicos cerebrales transitorios', 'Nervioso', 'G40-G47'),
('G46', 'Síndromes vasculares cerebrales', 'Nervioso', 'G40-G47'),
('G47', 'Trastornos del sueño', 'Nervioso', 'G40-G47'),
('G50', 'Trastornos del nervio trigémino', 'Nervioso', 'G50-G59'),
('G51', 'Trastornos del nervio facial', 'Nervioso', 'G50-G59'),
('G52', 'Trastornos de otros nervios craneales', 'Nervioso', 'G50-G59'),
('G53', 'Trastornos de nervios craneales en enfermedades clasificadas', 'Nervioso', 'G50-G59'),
('G54', 'Trastornos de raíces y plexos nerviosos', 'Nervioso', 'G50-G59'),
('G55', 'Compresiones de raíces nerviosas en enfermedades clasificadas', 'Nervioso', 'G50-G59'),
('G56', 'Mononeuropatías del miembro superior', 'Nervioso', 'G50-G59'),
('G57', 'Mononeuropatías del miembro inferior', 'Nervioso', 'G50-G59'),
('G58', 'Otras mononeuropatías', 'Nervioso', 'G50-G59'),
('G59', 'Mononeuropatías en enfermedades clasificadas', 'Nervioso', 'G50-G59'),
('G60', 'Neuropatía hereditaria y idiopática', 'Nervioso', 'G60-G64'),
('G61', 'Polineuropatía inflamatoria', 'Nervioso', 'G60-G64'),
('G62', 'Otras polineuropatías', 'Nervioso', 'G60-G64'),
('G63', 'Polineuropatía en enfermedades clasificadas', 'Nervioso', 'G60-G64'),
('G64', 'Otros trastornos del sistema nervioso periférico', 'Nervioso', 'G60-G64'),
('G70', 'Miastenia gravis', 'Nervioso', 'G70-G73'),
('G71', 'Trastornos musculares primarios', 'Nervioso', 'G70-G73'),
('G72', 'Otras miopatías', 'Nervioso', 'G70-G73'),
('G73', 'Trastornos musculares en enfermedades clasificadas', 'Nervioso', 'G70-G73'),
('G80', 'Parálisis cerebral infantil', 'Nervioso', 'G80-G83'),
('G81', 'Hemiplejía', 'Nervioso', 'G80-G83'),
('G82', 'Paraplejía y tetraplejía', 'Nervioso', 'G80-G83'),
('G83', 'Otros síndromes paralíticos', 'Nervioso', 'G80-G83'),
('G90', 'Trastornos del sistema nervioso autónomo', 'Nervioso', 'G90-G99'),
('G91', 'Hidrocefalia', 'Nervioso', 'G90-G99'),
('G92', 'Encefalopatía tóxica', 'Nervioso', 'G90-G99'),
('G93', 'Otros trastornos del encéfalo', 'Nervioso', 'G90-G99'),
('G94', 'Trastornos cerebrales en enfermedades clasificadas', 'Nervioso', 'G90-G99'),
('G95', 'Otras enfermedades de la médula espinal', 'Nervioso', 'G90-G99'),
('G96', 'Otros trastornos del SNC', 'Nervioso', 'G90-G99'),
('G97', 'Trastornos del SNC post-procedimientos', 'Nervioso', 'G90-G99'),
('G98', 'Otros trastornos del sistema nervioso', 'Nervioso', 'G90-G99'),
('G99', 'Trastornos del sistema nervioso en enfermedades clasificadas', 'Nervioso', 'G90-G99');